package com.adrenalinici.adrenaline.model;

public enum Action {
  MOVE_MOVE_MOVE,
  MOVE_PICKUP,
  SHOOT,
  MOVE_MOVE_PICKUP,
  MOVE_SHOOT,
  MOVE_RELOAD_SHOOT,
  MOVE_MOVE_MOVE_MOVE,
  MOVE_MOVE_RELOAD_SHOOT,
  MOVE_MOVE_MOVE_PICKUP
}
